CREATE TABLE IF NOT EXISTS posts_votes (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL,
  post_id BIGINT NOT NULL,
  up BOOLEAN NOT NULL DEFAULT FALSE,
  down BOOLEAN NOT NULL DEFAULT FALSE,
  refresh_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  CONSTRAINT fk_posts_votes_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_posts_votes_post FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
);